[project]
name = "pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.5.0",
    "pandas>=3.0.6",
    "psycopg2-binary>=2.9.13",
    "psycopg[binary]>=3.3.6",
    "pyarrow>=25.0.1",
    "sqlalchemy>=2.1.1",
    "tqdm>=4.70.1",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pgcli>=4.7.1",
]
